pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh script: '''
                    echo "I am in build step"
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Building DockerImage ="
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Pubishing DockerImage ="
                ''',
            label: "Publishing Docker Image"
            }
        }
    }
}
